### PR TITLE
Prepare for R

### PR DESCRIPTION
**Pull request by hmgaudecker**
All things from #105, which are not directly related to R.

Purpose: If in the (near) future somebody wants to add an example for Julia / Stata / ?, they will be able to check what changed in #105.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Hi @timmens, thanks for all your work! Thought I'd take a quick look but this of course was not enough. If micromamba is recent enough on GHA, I'd hope the above environmental variable should do. However, the way to go seems to be to set up a `.mambarc` file and point micromamba towards it, not sure how to best do that on GHA... Current failure the same as before, additional warning:

```
Warning: Unexpected input(s) 'use_lockfiles', valid inputs are ['environment-file', 'environment-name', 'micromamba-version', 'extra-specs', 'channels', 'condarc-file', 'channel-priority', 'cache-downloads', 'cache-downloads-key', 'cache-env', 'cache-env-key', 'log-level', 'installer-url', 'condarc-options', 'post-deinit']
```

**Comment by timmens** [comment]
First of all, sorry for pushing so many commits. But, the tests run now, although the windows tests are extremely slow. The checks still fail because the code coverage is too low.

## What I did

I am now running `pytest` directly instead of using `tox`. This allows me to create only one testing environment, namely when we call the conda incubator. As you proposed, this could be sped up using micromamba. It seems though, that this is not the bottleneck, as the longest running time occurs inside the pytest call; Most likely when the cookiecutter environment is created inside the test. As we are already using mamba there, I can't think of a quick fix to speed this up further.

**Comment by hmgaudecker** [comment]
Thanks!!! 

Just for me to understand: Code coverage fell because we are running those tests directly via pytest now as compared to previously via tox? Nothing substantively changed I guess?

And since I looked into it: Did you try running in parallel while disabling the lockfile? Runtime doesn|t matter much in the end, though.

**Comment by timmens** [comment]
1. The drop in coverage seems to be a bug. The "uncovered" lines are clearly covered by our tests.
2. No I did try disabling the lockfile and running it in parallel.

**Pull request merged**
