### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by Maxie02**
This PR adapts the documentation to the new structure.

There are three main changes:

1. Design change
We use the modern design from estimagic.
2. Structure change
Given the new structure of the templates, we adjust the structure of the documentation to be more modular and focus on the similarities and disparities of the programming languages.
3. Content change
We update the figures and text of the documentation in line with the new structure and the new example. Importantly this is only properly done for the Python section.

---

Things that need to be done at some point (referenced in #91):

- Work through comments of Maxie
- Add language-specific pytask / directory sections

### CODE REVIEW

**Comment by timmens** [comment]
Before this comment, Maxie worked on this PR. From here on I will take over.

**Comment by timmens** [comment]
TODO:

1. Create language specific dag and pytask sections
2. Fix warnings

**Review by hmgaudecker — COMMENTED** [review]
Wonderful! Really slick. Just very brief feedback, gotta run:

- [x] Running this via make html gives lots of errors because of missing comment directive?
- [ ] Getting Started page needs more structure (contents on the right have just one entry) and it somehow needs a closing paragraph (what's next)
- [ ] I would introduce the directory structure only once for all languages, between "getting started" and the actual descriptions of the examples. We can call the actual files then `clean_data{.py, .r, .jl, .do}` in the figures.
- [ ] Somehow I could not find the section "how to go about modifying example for your needs" anymore, maybe even make that a separate page, it is the most important thing after all.
- [x] The API docs can go, I think.

**Comment by timmens** [comment]
I restructured the documentation again. It should be better now. However, I don't know where the section "how to go about modifying example for your needs" is. Any idea in which version of the docs/templates this was included?

**Comment by hmgaudecker** [comment]
> I restructured the documentation again. It should be better now. 

Thanks, looks great! Will be a few days until I'll manage to read through them in detail.

> However, I don't know where the section "how to go about modifying example for your needs" is. Any idea in which version of the docs/templates this was included?

Sorry that was confusing indeed. I meant:

- Starting a new project from scratch
- Porting an existing project

Made them more prominent now and made sure the compilation does not give any warnings.

**Pull request merged**
